[project]
name = "llmserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.75.0",
    "grpcio-tools>=1.75.0",
    "langgraph>=0.6.7",
]
