package env

var (
	OLLAMA_SERVER_ADDRESS     = GetEnv("OLLAMA_SERVER_ADDRESS", "http://127.0.0.1:11434")
	OLLAMA_WAIT_TIME          = ToInt(GetEnv("OLLAMA_WAIT_TIME", "200"), 200)
	OLLAMA_MODEL_NAME         = GetEnv("OLLAMA_MODEL_NAME", "gtp-oss:20b")
	AGENT_WORKER_COUNT        = ToInt(GetEnv("AGENT_WORKER_COUNT", "20"), 100)
	WOKER_OUTPUT_FIFOQ_LENGTH = ToInt(GetEnv("WOKER_OUPUT_FIFOQ_LENGTH", "20"), 20)
)
